sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: isFCUOaPJ3+ruGNiQ5Xr/lEHLbfbC3Teel7JVqlbd8b0IGoppsOH4d+xj1BwkrPRKxj6cft6BG+XzCh9+PqQTimAOvyUDk5icg7C7ntzrFFP0ZIYwr9JVQCCOXvmFs334oJxmAq8EREdCcJgK5uy7zCGkiY5RjtPGwzxTOjw/ej4v67WvIbtzCkny+67rshac85ndPSJx7LONjZVRpPnVgYHxBtJGkc4Ik498odtyX1RJKjx8sx2Eyj45M5PgDDdItv81f4Hh+fwnU3VFUUQZ3NDn2PUm+vox2RNu3yzw9jDbgsvkrL32zrTFh82Mwo9cJVS6ScBQ9wJo3j8j0mZUGYt4w2LdVXeKmWzhhHy7nH3PyokrtmOMo8sDERRPVEWgIm9SbFUW4PA9lDEVXn7HGxX24ks/N3772PhIqoikCRTbKIckguoYV4i5exkWCXog4yIkImCqqh5oDnJ6tIMkFmxlU2r2tjRZkNw68BVLUicJUafw9sFDdawksUDfTi7H22OfBs4Ff5dxSFVvd0CHA01FWpErZu3Ek16NPqG/NtMTh+E9NpPVrMZ6PAtWs+kx4pT4kZ+VJ+Hi+VBV5PS1bpEv8grHRcYc7d6lN9suWMn+jIsyE7mgpWinlfgkro2hiOAv4f6ADuxjRFQrQrBev8KaejpJIqfpiSIo3JGaNg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Troll-Garden-and-Selected-Stories_346
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy